[package]
edition = "2021"
license.workspace = true
name = "codex-utils-pty"
version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
portable-pty = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time"] }

[target.'cfg(windows)'.dependencies]
filedescriptor = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
shared_library = { workspace = true }
winapi = { features = [
    "handleapi",
    "minwinbase",
    "processthreadsapi",
    "synchapi",
    "winbase",
    "wincon",
    "winerror",
    "winnt",
] , workspace = true }
