[package]
name = "codex-cloud-tasks-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "codex_cloud_tasks_client"
path = "src/lib.rs"

[lints]
workspace = true

[features]
default = ["online"]
online = ["dep:codex-backend-client"]
mock = []

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { features = ["serde"] , workspace = true }
diffy = { workspace = true }
serde = { features = ["derive"] , workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
codex-backend-client = { path = "../backend-client", optional = true }
codex-git = { workspace = true }
